os: osx
language: swift
osx_image: xcode11.5
xcode_project: PokemonAPI.xcodeproj
xcode_scheme: PokemonAPI
cache: cocoapods
podfile: Example/Podfile
env:
  global:
    - FRAMEWORK_NAME=PokemonAPI
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  # Commented out due to error NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9807)
  # - xcodebuild -project PokemonAPI.xcodeproj -scheme "PokemonAPI iOS" -sdk iphonesimulator12.2 build-for-testing
  # - xctool -project PokemonAPI.xcodeproj -scheme "PokemonAPI iOS" run-tests -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,name=iPhone Xs'

  - xcodebuild -project PokemonAPI.xcodeproj -scheme "PokemonAPI OSX" -sdk macosx10.15 build-for-testing
  - xctool -project PokemonAPI.xcodeproj -scheme "PokemonAPI OSX" run-tests -sdk macosx10.15

  # Commented out due to error NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9807)
  # - xcodebuild -project PokemonAPI.xcodeproj -scheme "PokemonAPI tvOS" -sdk appletvsimulator12.2 build-for-testing
  # - xctool -project PokemonAPI.xcodeproj -scheme "PokemonAPI tvOS" run-tests -sdk appletvsimulator12.2 -destination 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K'

  - pod lib lint --allow-warnings --quick
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: zNeWHJ+zUWOpc3hEeOAvoqmeknlM/wyjFizj6zAQ5Ow5Ep0yLIrtgUZHtENehFt6QxJQFttdX+4bK8pmJU8B9AovPk6iZcXoF9zAamyUHuMNdcIhkMyEVjuuekrQIcnDANGUhJGPHbGZ0vbIr+rf1YQ/t5Ob0YlHn/ckw8sJ14wRCjhFF6dgol/2AzvAFbxrYXBMtKZw2Vz9kI9wkTYDGy1vCnSFOdyRfWoYLaBgEfBV7p0ryHuKuXhhUz7Qxv8BxJvAB11QhCKCfXLC1YLCnkJEzy0k2b7x0j4xhZrgsi5BiCyRPbDICe0Ykjk/cNwRp/gIBqDEw0vofCm0wmAJ+94oudI2U+K8EzchawHF8aIACkEh1wxWzIczG+jgINm6TY1K8DEL4sfskw4KMYTazy7XnNHLtnBtwn/GNbiS+vP99NHTHR6a0RsPpizi+TcamntOfm0ayUHQH3cqQqr+DeAu18FkxclvIWrxNNf6zpFqcs73MZTbVitR6F9UAH8hnDJU/yCm1FO+am0bCfHnJL17Z9L36HshLa9bG4hzvw/+rU7Qvb1nkoR31CB0tc5SIeCvDS017KOm8XJTknZz7XnGPT15eOcVpxlfTlmooStt2gaDFxxNzO8qnDREwiEqgY5sIN3tAZolInFb9Y9XKjdoEd2HBmHFqAghVpGhSUs=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: kinkofer/PokemonAPI
    tags: true
